Added Ben-Or asynchronous consensus algorithm
krzysztof-turowski/distributed-framework pull request #15
Opened 2022-01-10 20:41 UTC by tmarzec

2022-01-12 18:06 UTC, krzysztof-turowski requested changes
First round of suggestions - please synchronize PR with recent changes and consider how to align runBenOr with the code of runHumblet to make them as similar as possible.

I would think of it independently and we'll reach some agreement in the next round, I suppose.

2022-01-13 14:47 UTC, tmarzec commented on Makefile
> +	go run example/async_ben_or.go 6 1
Done, https://github.com/tmarzec/distributed-framework/blob/91cac47f258419694da1fd8e4a564771a5eac642/Makefile#L29-L30

2022-01-13 14:50 UTC, tmarzec commented on consensus/ben_or/ben-or.go
> +	msgDecided		= 1
Done.

2022-01-13 14:55 UTC, tmarzec commented on consensus/ben_or/ben-or.go
> +}
Added.

2022-01-13 14:56 UTC, tmarzec commented on lib/lib_nodes.go
> +}
Added.

2022-01-13 15:00 UTC, tmarzec commented on consensus/ben_or/ben-or.go
> +		if starting := (*v).node.GetState()[0]; starting == firstBit {
It does, I've changed it now.

2022-01-13 15:02 UTC, tmarzec commented on consensus/ben_or/ben-or.go
> +	firstBit := (*vertices[0]).node.GetState()[1]
Done.

2022-01-13 15:06 UTC, tmarzec commented on consensus/ben_or/ben-or.go
> +type messageTypeBenOr int
Done, I've changed it to: 
```golang
type messageTypeBenOr int


const (
	msgTypeOne messageTypeBenOr = iota
	msgTypeTwo
)
```

2022-01-17 17:28 UTC, krzysztof-turowski approved these changes
Thank you very much, aaside from the nice PR, the whole discussion was very fruitful and it clarified a lot for future development. Please run "go fmt" and add missing blank line (see comment) and you're good to go!

2022-01-17 17:28 UTC, krzysztof-turowski commented on lib/lib_graph_weighted.go
> +}
Please add a blank line at the end

2022-01-17 18:30 UTC, merged