Add async franklin algorithm implementation
krzysztof-turowski/distributed-framework pull request #23
Opened 2023-01-25 20:58 UTC by tymoteusz-chelmecki

2023-01-30 12:55 UTC, krzysztof-turowski requested changes
Thank you very much - just small changes in the code needed, would you be finishing it or should I do it on my own?

2023-01-30 12:55 UTC, krzysztof-turowski commented on leader/undirected_ring/async_franklin/async_franklin.go
> +func handleTwoMessages(node lib.Node, first int, second int, firstMsgBytes []byte) (uint64, uint64) {
first parameter is not used, please consider refactoring the function

2023-01-30 12:55 UTC, krzysztof-turowski commented on leader/undirected_ring/async_franklin/async_franklin.go
> +		if sender == LEFT {
Please consider:
other := RIGHT
if sender == RIGHT {
  other = LEFT
}
decodeAll(byteMsg, &msg)
node.SendMessage(other, byteMsg)
if msg.IsFinal {
  setFinalState(node, msg.Value, false)
  return
}

2023-01-30 14:45 UTC, krzysztof-turowski reviewed
Just one more thing: please add appropriate info to Makefile and README

2023-01-30 19:53 UTC, tymoteusz-chelmecki commented
I've added requested changes in a new commit.

2023-02-05 05:34 UTC, krzysztof-turowski approved these changes
Thank you very much for this nice contribution

2023-02-05 05:36 UTC, merged