Itai-Rodeh on async directed ring
krzysztof-turowski/distributed-framework pull request #52
Opened 2024-12-19 23:09 UTC by Skryg

2025-01-21 19:52 UTC, krzysztof-turowski requested changes
Thank you very much, some suggestions provided.

2025-01-21 19:52 UTC, krzysztof-turowski commented on example/leader_directed_ring_async.go
> +	async_itah_rodeh_2 "github.com/Skryg/distributed-framework/leader/directed_ring/async_itai_rodeh_2"
Please remove this alias

2025-01-21 19:52 UTC, krzysztof-turowski commented on go.mod
> +module github.com/Skryg/distributed-framework
Why did you change the name? It wouldn't work in master ;)

2025-01-21 19:52 UTC, krzysztof-turowski commented on go.mod
> +require github.com/krzysztof-turowski/distributed-framework v0.0.0-20240127132939-ef4f11a7b6da // indirect
Is it necessary?

2025-01-21 19:52 UTC, krzysztof-turowski commented on example/leader_directed_ring_async.go
> +		async_itah_rodeh_2.RunDefault(n)
Why RunDefault and not Run?

2025-01-21 19:52 UTC, krzysztof-turowski commented on test/leader_directed_ring_test.go
> +	async_itah_rodeh_2.Run(n, int(math.Log2(float64(n))/5.), getRandBit())
OK, please stay with 2-parameter `Run(n, p)`, but hide random bits inside, like in other I-R implementations

2025-01-21 19:52 UTC, krzysztof-turowski commented on Makefile
> +
Nit: remove empty line

2025-01-21 19:52 UTC, krzysztof-turowski commented on example/leader_directed_ring_async.go
> +
Nit: remove empty line. Consider running `make format`

2025-01-26 19:26 UTC, Skryg commented on go.mod
> +module github.com/Skryg/distributed-framework
Oh, I had a problem with importing modules and I tried several ways to resolve it, so I must have forgotten to bring it back

2025-01-26 19:32 UTC, Skryg commented on test/leader_directed_ring_test.go
> +	async_itah_rodeh_2.Run(n, int(math.Log2(float64(n))/5.), getRandBit())
I made `Run(n)` to have only one parameter and added `RunProb(n,p)`. I think it is now more consistent Is that OK?

2025-01-28 18:30 UTC, krzysztof-turowski approved these changes
Thank you very much for your contribution!

2025-01-28 18:30 UTC, merged